MODEL:
  NAME: resnet50
  NUM_CLASSES: 124
  POOL: gem
  HEADS:
    IN_FEAT: 2048
    REDUCTION_DIM: 512
    MARGIN: 0.15
    SCALE: 30

INPUT:
  SIZE_CROP: [448,448]
  SIZE_INPUT: [480, 480]
  SIZE_TEST: [448, 448]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  DROPOUTPORB: 0.5
  DATAPATH: ../../datasets/data/train
  CKPTPATH: ../../out/tricls/model_best.pyth

BN:
  ZERO_INIT_FINAL_GAMMA: True

OPTIM:
  BASE_LR: 0.001
  LR_POLICY: cos
  STEPS: [0, 30, 60, 90]
  LR_MULT: 0.1
  MAX_EPOCH: 2000
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0001
  WARMUP_EPOCHS: 5
TRAIN:
  DATASET: GLDv2
  SPLIT: train_list.txt
  BATCH_SIZE: 128
  IM_SIZE: 512
  EVAL_PERIOD: 100
  GPU: [0,1,2,3,4,5,6,7,8]

TEST:
  DATASET: GLDv2
  SPLIT: val_list.txt
  BATCH_SIZE: 64
  IM_SIZE: 256

DATALOADER:
  NUM_WORKERS: 4
  NUM_INSTANCE: 6
CUDNN:
  BENCHMARK: True
OUT_DIR: ./output_origin
